### ISSUE TITLE
Cannot connect to https://cloud.zilliz.com

### ISSUE THREAD

**Issue by minhhieugma** [milvus-io/milvus-sdk-csharp#8]
Basically the SDK cannot connect to collections on `https://cloud.zilliz.com`. It says `auth check failure, please check username and password are correct`.

```
public const string Host = "in01-XXXXXXXXX.aws-us-west-2.vectordb.zillizcloud.com";
public const int Port = 19543;

connect.UseHttps = true;
```

Exception Details
```
Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="auth check failure, please check username and password are correct")
   at Grpc.Net.Client.Internal.HttpClientCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Milvus.Proto.Milvus.MilvusService.MilvusServiceClient.Query(QueryRequest request, CallOptions options) in /Users/hieu/sources/repos/milvus-sdk-csharp/src/IO.Milvus/obj/Debug/net7.0/MilvusGrpc.cs:line 2030
   at IO.Milvus.Client.AbstractMilvusGrpcClient.Query(QueryParam requestParam, Nullable`1 callOptions) in /Users/hieu/sources/repos/milvus-sdk-csharp/src/IO.Milvus/Client/AbstractMilvusGrpcClient.cs:line 1337
```

**Comment by xiaofan-luan** [comment]
seems that the verification failed.
You will need to offer username/password.
Did the c# client support username/password

**Comment by minhhieugma** [comment]
I have found the reason. In short, the current sdk does not work with a remote Milvus server at all. It only works locally to some extend.

I made a PR to fix it and other issues: https://github.com/milvus-io/milvus-sdk-csharp/pull/9
